<?php

// Traduzido por Marcelo Leães
// marcelo@eth1.com.br - Eth1 Consultoria

$labels = array();
$labels['forwarding'] = 'Encaminhar';
$labels['editforwarding'] = 'Editar encaminhamento';
$labels['enabled'] = 'Habilitado';
$labels['address'] = 'Endereço de e-mail';
$labels['keeporiginalmessage'] = 'Manter mensagem original na caixa do usuário';
$messages = array();
$messages['novalidemailaddress'] = 'O endereço informado não é um endereço de e-mail válido.';
$messages['successfullyupdated'] = 'Emcaminhamento atualizado com sucesso.';
$messages['internalerror'] = 'Ocorreu um erro com a ação selecionada.';
//$messages['connecterror'] = $messages['internalerror'] . ' Erro de conexão.';
$messages['loaderror'] = 'Não foi possivel carregar o encaminhamento.';
$messages['loadconnecterror'] = $messages['loadinternalerror'] . ' Erro de conexão.';
$messages['updateerror'] = 'Não foi possivel atualizar a conta.';
$messages['updateconnecterror'] = $messages['updateerror'] . ' Erro de conexão.';
